// Periodic table element data
export interface Element {
  atomicNumber: number;
  symbol: string;
  name: string;
  atomicMass: number;
  category: string;
  group: number;
  period: number;
  block: string;
  electronConfiguration: string;
  appearance?: string;
  electronegativity?: number;
  atomicRadius?: number;
  ionizationEnergy?: number | string;
  electronAffinity?: number;
  meltingPoint?: number;
  boilingPoint?: number;
  density?: number;
  discoveredBy?: string;
  discoveryYear?: number;
  description: string;
  valenceElectrons: number;
  reactivity: 'very reactive' | 'reactive' | 'moderately reactive' | 'low reactivity' | 'inert';
  state: 'solid' | 'liquid' | 'gas' | 'unknown';
  color: string;
  
  // Additional fields from CSV
  molarHeat?: number;
  namedBy?: string;
  phase?: string;
  source?: string;
  xpos?: number;
  ypos?: number;
  wxpos?: number;
  wypos?: number;
  shells?: string;
  imageTitle?: string;
  imageUrl?: string;
}

export const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: 1.008,
    category: 'nonmetal',
    group: 1,
    period: 1,
    block: 's',
    electronConfiguration: '1s¹',
    appearance: 'Colorless gas',
    electronegativity: 2.20,
    atomicRadius: 53,
    ionizationEnergy: 1312,
    electronAffinity: 73,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    density: 0.00008988,
    discoveredBy: 'Henry Cavendish',
    discoveryYear: 1766,
    description: 'The lightest element, hydrogen is the most abundant chemical substance in the universe.',
    valenceElectrons: 1,
    reactivity: 'reactive',
    state: 'gas',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: 4.0026,
    category: 'noble gas',
    group: 18,
    period: 1,
    block: 's',
    electronConfiguration: '1s²',
    appearance: 'Colorless gas',
    electronegativity: undefined,
    atomicRadius: 31,
    ionizationEnergy: 2372,
    electronAffinity: 0,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    density: 0.0001785,
    discoveredBy: 'Pierre Janssen',
    discoveryYear: 1868,
    description: 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas.',
    valenceElectrons: 2,
    reactivity: 'inert',
    state: 'gas',
    color: '#4ecdc4'
  },

  // Period 2
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: 6.94,
    category: 'alkali metal',
    group: 1,
    period: 2,
    block: 's',
    electronConfiguration: '[He] 2s¹',
    appearance: 'Silvery-white',
    electronegativity: 0.98,
    atomicRadius: 167,
    ionizationEnergy: 520,
    electronAffinity: 60,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    density: 0.534,
    discoveredBy: 'Johan August Arfwedson',
    discoveryYear: 1817,
    description: 'Lithium is a soft, silvery-white alkali metal that is highly reactive.',
    valenceElectrons: 1,
    reactivity: 'very reactive',
    state: 'solid',
    color: '#ffd93d'
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: 9.0122,
    category: 'alkaline earth metal',
    group: 2,
    period: 2,
    block: 's',
    electronConfiguration: '[He] 2s²',
    appearance: 'White-gray metallic',
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 900,
    electronAffinity: 0,
    meltingPoint: 1287,
    boilingPoint: 2471,
    density: 1.85,
    discoveredBy: 'Louis Nicolas Vauquelin',
    discoveryYear: 1798,
    description: 'Beryllium is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei.',
    valenceElectrons: 2,
    reactivity: 'reactive',
    state: 'solid',
    color: '#6bcf7f'
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: 10.81,
    category: 'metalloid',
    group: 13,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p¹',
    appearance: 'Black-brown',
    electronegativity: 2.04,
    atomicRadius: 87,
    ionizationEnergy: 801,
    electronAffinity: 27,
    meltingPoint: 2075,
    boilingPoint: 4000,
    density: 2.34,
    discoveredBy: 'Joseph Louis Gay-Lussac',
    discoveryYear: 1808,
    description: 'Boron is a metalloid element that occurs in trace amounts in the Earth\'s crust.',
    valenceElectrons: 3,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#4d96ff'
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: 12.011,
    category: 'nonmetal',
    group: 14,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p²',
    appearance: 'Black solid',
    electronegativity: 2.55,
    atomicRadius: 67,
    ionizationEnergy: 1087,
    electronAffinity: 122,
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    discoveredBy: 'Ancient times',
    discoveryYear: undefined,
    description: 'Carbon is the fourth most abundant element in the universe and the basis of life on Earth.',
    valenceElectrons: 4,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: 14.007,
    category: 'nonmetal',
    group: 15,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p³',
    appearance: 'Colorless gas',
    electronegativity: 3.04,
    atomicRadius: 56,
    ionizationEnergy: 1402,
    electronAffinity: 7,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    density: 0.0012506,
    discoveredBy: 'Daniel Rutherford',
    discoveryYear: 1772,
    description: 'Nitrogen is the most abundant element in Earth\'s atmosphere and is essential for life.',
    valenceElectrons: 5,
    reactivity: 'reactive',
    state: 'gas',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: 15.999,
    category: 'nonmetal',
    group: 16,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁴',
    appearance: 'Colorless gas',
    electronegativity: 3.44,
    atomicRadius: 48,
    ionizationEnergy: 1314,
    electronAffinity: 141,
    meltingPoint: -218.3,
    boilingPoint: -182.9,
    density: 0.001429,
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveryYear: 1773,
    description: 'Oxygen is essential for respiration in most living organisms and makes up about 21% of Earth\'s atmosphere.',
    valenceElectrons: 6,
    reactivity: 'reactive',
    state: 'gas',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: 18.998,
    category: 'halogen',
    group: 17,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁵',
    appearance: 'Pale yellow-green gas',
    electronegativity: 3.98,
    atomicRadius: 42,
    ionizationEnergy: 1681,
    electronAffinity: 328,
    meltingPoint: -219.6,
    boilingPoint: -188.1,
    density: 0.001696,
    discoveredBy: 'Henri Moissan',
    discoveryYear: 1886,
    description: 'Fluorine is the most electronegative element and the most reactive of all elements.',
    valenceElectrons: 7,
    reactivity: 'very reactive',
    state: 'gas',
    color: '#ff9500'
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: 20.180,
    category: 'noble gas',
    group: 18,
    period: 2,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁶',
    electronegativity: undefined,
    atomicRadius: 38,
    ionizationEnergy: 2081,
    electronAffinity: 0,
    meltingPoint: -248.6,
    boilingPoint: -246.1,
    density: 0.0008999,
    discoveredBy: 'William Ramsay',
    discoveryYear: 1898,
    description: 'Neon is a noble gas that produces an orange-red glow when used in lighting.',
    valenceElectrons: 8,
    reactivity: 'inert',
    state: 'gas',
    color: '#4ecdc4'
  },

  // Period 3
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: 22.990,
    category: 'alkali metal',
    group: 1,
    period: 3,
    block: 's',
    electronConfiguration: '[Ne] 3s¹',
    electronegativity: 0.93,
    atomicRadius: 190,
    ionizationEnergy: 496,
    electronAffinity: 53,
    meltingPoint: 97.72,
    boilingPoint: 883,
    density: 0.968,
    discoveredBy: 'Humphry Davy',
    discoveryYear: 1807,
    description: 'Sodium is a soft, silvery-white, highly reactive metal that is essential for life.',
    valenceElectrons: 1,
    reactivity: 'very reactive',
    state: 'solid',
    color: '#ffd93d'
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: 24.305,
    category: 'alkaline earth metal',
    group: 2,
    period: 3,
    block: 's',
    electronConfiguration: '[Ne] 3s²',
    electronegativity: 1.31,
    atomicRadius: 145,
    ionizationEnergy: 738,
    electronAffinity: 0,
    meltingPoint: 650,
    boilingPoint: 1090,
    density: 1.738,
    discoveredBy: 'Joseph Black',
    discoveryYear: 1755,
    description: 'Magnesium is essential for life and is found in chlorophyll, which plants use for photosynthesis.',
    valenceElectrons: 2,
    reactivity: 'reactive',
    state: 'solid',
    color: '#6bcf7f'
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicMass: 26.982,
    category: 'post-transition metal',
    group: 13,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    atomicRadius: 118,
    ionizationEnergy: 578,
    electronAffinity: 43,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    density: 2.698,
    discoveredBy: 'Hans Christian Ørsted',
    discoveryYear: 1825,
    description: 'Aluminum is the most abundant metal in Earth\'s crust and is widely used in industry.',
    valenceElectrons: 3,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#c084fc'
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: 28.085,
    category: 'metalloid',
    group: 14,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p²',
    electronegativity: 1.90,
    atomicRadius: 111,
    ionizationEnergy: 787,
    electronAffinity: 134,
    meltingPoint: 1414,
    boilingPoint: 3265,
    density: 2.3296,
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveryYear: 1824,
    description: 'Silicon is the second most abundant element in Earth\'s crust and is essential for semiconductor technology.',
    valenceElectrons: 4,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#4d96ff'
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: 30.974,
    category: 'nonmetal',
    group: 15,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 1012,
    electronAffinity: 72,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    density: 1.823,
    discoveredBy: 'Hennig Brand',
    discoveryYear: 1669,
    description: 'Phosphorus is essential for life and is a key component of DNA, RNA, and ATP.',
    valenceElectrons: 5,
    reactivity: 'reactive',
    state: 'solid',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: 32.06,
    category: 'nonmetal',
    group: 16,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 1000,
    electronAffinity: 200,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    density: 2.067,
    discoveredBy: 'Ancient times',
    discoveryYear: undefined,
    description: 'Sulfur is essential for life and is found in amino acids and vitamins.',
    valenceElectrons: 6,
    reactivity: 'reactive',
    state: 'solid',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: 35.45,
    category: 'halogen',
    group: 17,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 1251,
    electronAffinity: 349,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    density: 0.003214,
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveryYear: 1774,
    description: 'Chlorine is a highly reactive halogen that is used for water purification and as a disinfectant.',
    valenceElectrons: 7,
    reactivity: 'very reactive',
    state: 'gas',
    color: '#ff9500'
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: 39.948,
    category: 'noble gas',
    group: 18,
    period: 3,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁶',
    electronegativity: undefined,
    atomicRadius: 71,
    ionizationEnergy: 1521,
    electronAffinity: 0,
    meltingPoint: -189.3,
    boilingPoint: -185.8,
    density: 0.0017837,
    discoveredBy: 'Lord Rayleigh',
    discoveryYear: 1894,
    description: 'Argon is the third most abundant gas in Earth\'s atmosphere and is used in light bulbs.',
    valenceElectrons: 8,
    reactivity: 'inert',
    state: 'gas',
    color: '#4ecdc4'
  },

  // Period 4 - Transition Metals
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: 39.098,
    category: 'alkali metal',
    group: 1,
    period: 4,
    block: 's',
    electronConfiguration: '[Ar] 4s¹',
    electronegativity: 0.82,
    atomicRadius: 243,
    ionizationEnergy: 419,
    electronAffinity: 48,
    meltingPoint: 63.38,
    boilingPoint: 759,
    density: 0.862,
    discoveredBy: 'Humphry Davy',
    discoveryYear: 1807,
    description: 'Potassium is essential for life and is important for nerve function and muscle contraction.',
    valenceElectrons: 1,
    reactivity: 'very reactive',
    state: 'solid',
    color: '#ffd93d'
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: 40.078,
    category: 'alkaline earth metal',
    group: 2,
    period: 4,
    block: 's',
    electronConfiguration: '[Ar] 4s²',
    electronegativity: 1.00,
    atomicRadius: 194,
    ionizationEnergy: 590,
    electronAffinity: 2,
    meltingPoint: 842,
    boilingPoint: 1484,
    density: 1.54,
    discoveredBy: 'Humphry Davy',
    discoveryYear: 1808,
    description: 'Calcium is essential for life and is the most abundant metal in the human body.',
    valenceElectrons: 2,
    reactivity: 'reactive',
    state: 'solid',
    color: '#6bcf7f'
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: 44.956,
    category: 'transition metal',
    group: 3,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    atomicRadius: 184,
    ionizationEnergy: 633,
    electronAffinity: 18,
    meltingPoint: 1541,
    boilingPoint: 2836,
    density: 2.985,
    discoveredBy: 'Lars Fredrik Nilson',
    discoveryYear: 1879,
    description: 'Scandium is a rare earth element used in aerospace components and sports equipment.',
    valenceElectrons: 3,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: 47.867,
    category: 'transition metal',
    group: 4,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    atomicRadius: 176,
    ionizationEnergy: 659,
    electronAffinity: 8,
    meltingPoint: 1668,
    boilingPoint: 3287,
    density: 4.506,
    discoveredBy: 'William Gregor',
    discoveryYear: 1791,
    description: 'Titanium is a strong, lightweight metal used in aerospace, medical implants, and jewelry.',
    valenceElectrons: 4,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: 50.942,
    category: 'transition metal',
    group: 5,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    atomicRadius: 171,
    ionizationEnergy: 651,
    electronAffinity: 51,
    meltingPoint: 1910,
    boilingPoint: 3407,
    density: 6.11,
    discoveredBy: 'Andrés Manuel del Río',
    discoveryYear: 1801,
    description: 'Vanadium is used in steel alloys to increase strength and is essential for some enzymes.',
    valenceElectrons: 5,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: 51.996,
    category: 'transition metal',
    group: 6,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    atomicRadius: 166,
    ionizationEnergy: 653,
    electronAffinity: 64,
    meltingPoint: 1907,
    boilingPoint: 2671,
    density: 7.15,
    discoveredBy: 'Louis Nicolas Vauquelin',
    discoveryYear: 1797,
    description: 'Chromium is used for chrome plating and is essential for glucose metabolism.',
    valenceElectrons: 6,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: 54.938,
    category: 'transition metal',
    group: 7,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    atomicRadius: 161,
    ionizationEnergy: 717,
    electronAffinity: 0,
    meltingPoint: 1246,
    boilingPoint: 2061,
    density: 7.44,
    discoveredBy: 'Torbern Bergman',
    discoveryYear: 1770,
    description: 'Manganese is essential for steel production and is important for bone health.',
    valenceElectrons: 7,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: 55.845,
    category: 'transition metal',
    group: 8,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    atomicRadius: 156,
    ionizationEnergy: 763,
    electronAffinity: 16,
    meltingPoint: 1538,
    boilingPoint: 2861,
    density: 7.874,
    discoveredBy: 'Ancient times',
    discoveryYear: undefined,
    description: 'Iron is the most common element on Earth and is essential for life (hemoglobin).',
    valenceElectrons: 8,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: 58.933,
    category: 'transition metal',
    group: 9,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    atomicRadius: 152,
    ionizationEnergy: 760,
    electronAffinity: 64,
    meltingPoint: 1495,
    boilingPoint: 2927,
    density: 8.86,
    discoveredBy: 'Georg Brandt',
    discoveryYear: 1735,
    description: 'Cobalt is used in batteries and is essential for vitamin B12 production.',
    valenceElectrons: 9,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: 58.693,
    category: 'transition metal',
    group: 10,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    atomicRadius: 149,
    ionizationEnergy: 737,
    electronAffinity: 112,
    meltingPoint: 1455,
    boilingPoint: 2913,
    density: 8.902,
    discoveredBy: 'Axel Fredrik Cronstedt',
    discoveryYear: 1751,
    description: 'Nickel is used in stainless steel and coins, and is essential for some enzymes.',
    valenceElectrons: 10,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: 63.546,
    category: 'transition metal',
    group: 11,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.90,
    atomicRadius: 145,
    ionizationEnergy: 746,
    electronAffinity: 119,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    density: 8.96,
    discoveredBy: 'Ancient times',
    discoveryYear: undefined,
    description: 'Copper is an excellent conductor of electricity and is essential for life.',
    valenceElectrons: 11,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: 65.38,
    category: 'transition metal',
    group: 12,
    period: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    atomicRadius: 142,
    ionizationEnergy: 906,
    electronAffinity: 0,
    meltingPoint: 419.53,
    boilingPoint: 907,
    density: 7.134,
    discoveredBy: 'Andreas Sigismund Marggraf',
    discoveryYear: 1746,
    description: 'Zinc is essential for immune function and is used in galvanizing steel.',
    valenceElectrons: 12,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#ff6b9d'
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: 69.723,
    category: 'post-transition metal',
    group: 13,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    atomicRadius: 136,
    ionizationEnergy: 579,
    electronAffinity: 29,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    density: 5.907,
    discoveredBy: 'Lecoq de Boisbaudran',
    discoveryYear: 1875,
    description: 'Gallium has the longest liquid range of any element and is used in semiconductors.',
    valenceElectrons: 3,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#c084fc'
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: 72.63,
    category: 'metalloid',
    group: 14,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    atomicRadius: 125,
    ionizationEnergy: 762,
    electronAffinity: 119,
    meltingPoint: 938.3,
    boilingPoint: 2820,
    density: 5.323,
    discoveredBy: 'Clemens Winkler',
    discoveryYear: 1886,
    description: 'Germanium is used in fiber optics and infrared optics.',
    valenceElectrons: 4,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#4d96ff'
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: 74.922,
    category: 'metalloid',
    group: 15,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    atomicRadius: 114,
    ionizationEnergy: 947,
    electronAffinity: 78,
    meltingPoint: 817,
    boilingPoint: 613,
    density: 5.776,
    discoveredBy: 'Albertus Magnus',
    discoveryYear: 1250,
    description: 'Arsenic is toxic but has medical uses in small doses.',
    valenceElectrons: 5,
    reactivity: 'moderately reactive',
    state: 'solid',
    color: '#4d96ff'
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: 78.971,
    category: 'nonmetal',
    group: 16,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    atomicRadius: 103,
    ionizationEnergy: 941,
    electronAffinity: 195,
    meltingPoint: 221,
    boilingPoint: 685,
    density: 4.809,
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveryYear: 1817,
    description: 'Selenium is essential for life and is used in photocells and solar panels.',
    valenceElectrons: 6,
    reactivity: 'reactive',
    state: 'solid',
    color: '#ff6b6b'
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: 79.904,
    category: 'halogen',
    group: 17,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    atomicRadius: 94,
    ionizationEnergy: 1140,
    electronAffinity: 325,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    density: 3.122,
    discoveredBy: 'Antoine Jérôme Balard',
    discoveryYear: 1826,
    description: 'Bromine is the only nonmetallic element that is liquid at room temperature.',
    valenceElectrons: 7,
    reactivity: 'very reactive',
    state: 'liquid',
    color: '#ff9500'
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: 83.798,
    category: 'noble gas',
    group: 18,
    period: 4,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    electronegativity: 3.00,
    atomicRadius: 88,
    ionizationEnergy: 1351,
    electronAffinity: 0,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    density: 0.003733,
    discoveredBy: 'William Ramsay',
    discoveryYear: 1898,
    description: 'Krypton is used in fluorescent lights and was discovered through spectroscopy.',
    valenceElectrons: 8,
    reactivity: 'inert',
    state: 'gas',
    color: '#4ecdc4'
  }
];

// Helper functions
export const getElementByAtomicNumber = (atomicNumber: number): Element | undefined => {
  return elements.find(el => el.atomicNumber === atomicNumber);
};

export const getElementsByCategory = (category: string): Element[] => {
  return elements.filter(el => el.category === category);
};

export const getElementsByPeriod = (period: number): Element[] => {
  return elements.filter(el => el.period === period);
};

export const getElementsByGroup = (group: number): Element[] => {
  return elements.filter(el => el.group === group);
};

export const getCategoryColor = (category: string): string => {
  const colorMap: Record<string, string> = {
    'alkali metal': '#ffd93d',
    'alkaline earth metal': '#6bcf7f',
    'transition metal': '#ff6b9d',
    'post-transition metal': '#c084fc',
    'metalloid': '#4d96ff',
    'nonmetal': '#ff6b6b',
    'halogen': '#ff9500',
    'noble gas': '#4ecdc4',
    'lanthanoid': '#ff6b35',
    'actinoid': '#ff4757'
  };
  return colorMap[category] || '#gray';
};

// CSV Data Loader
export { loadElementsFromCSV } from './csv-parser';